### ISSUE TITLE
React Native Quill Editor not working

### ISSUE THREAD

**Issue by AdarshMishraji** [youngjuning/react-native-quill-editor#1]
I have wrote the following code

`import React from 'react';
import QuillEditor from 'react-native-quill-editor';

const Quill = () => {
    const onChange = (html) => {
        console.log(html)
    }
    return <QuillEditor style={{ height: 300 }} placeholder="drxfgwrstedhgrstd" onChange={onChange} />
}

export default Quill;`

and it returns an error, which is preventing my app to load. And also this component.

![Screenshot from 2021-01-03 22-26-03](https://user-images.githubusercontent.com/39414583/103484254-6291ce80-4e13-11eb-8de0-1523511758f2.png)

**Comment by zisheng-ai** [comment]
This situation is usually caused by the occupation of port 8081 on the computer, because React Native will start the nodejs service on port 8081, and debugging on the mobile phone depends on this service.

**Comment by AdarshMishraji** [comment]
what I will do to resolve this issue?

**Comment by zisheng-ai** [comment]
Please try this: https://stackoverflow.com/questions/38870710/error-could-not-get-batchedbridge-make-sure-your-bundle-is-packaged-properly

**Comment by zisheng-ai** [comment]
Maybe you don't config react-native-webview
