### ISSUE TITLE
Cannot build the app

### ISSUE THREAD

**Issue by chuyenim** [youngjuning/react-native-quill-editor#2]
Hi,
I got an error when building the app:

`[Tue Jan 26 2021 15:14:46.970]  ERROR    Invariant Violation: Tried to register two views with the same name RNCWebView
[Tue Jan 26 2021 15:14:46.971]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Jan 26 2021 15:14:48.600]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

I found **react-native-webview** in the main node_modules, however I also found it in the child node_modules under react-native-quill-editor module:

/node_modules/**react-native-webview**  (image 1)
/node_modules/react-native-quill-editor/node_modules/**react-native-webview** (image 2)

![Imgur](https://i.imgur.com/JPjBcCa.png)
![Imgur](https://i.imgur.com/mNLs91J.png)

I see "react-native-webview" again in the react-native-quill-editor node_modules folder!??

![Imgur](https://i.imgur.com/cQOQVc2.png)

**Comment by zisheng-ai** [comment]
I will remove it from dependencies.

**Comment by zisheng-ai** [comment]
fix in react-native-quill-editor@0.2.0
